# Generated by Django 3.0.3 on 2020-07-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('host', models.CharField(max_length=100)),
                ('src', models.IntegerField()),
                ('proto', models.CharField(max_length=10)),
                ('type', models.IntegerField()),
                ('spt', models.IntegerField()),
                ('dpt', models.IntegerField()),
                ('srcstr', models.CharField(max_length=20)),
                ('cc', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=50)),
                ('locale', models.CharField(max_length=200)),
                ('localeabbr', models.CharField(max_length=10)),
                ('postalcode', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
