# Generated by Django 3.0.3 on 2020-07-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='cc',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='attack',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attack',
            name='datetime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='dpt',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='host',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attack',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='locale',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attack',
            name='localeabbr',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='attack',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='postalcode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='spt',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='src',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='srcstr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attack',
            name='type',
            field=models.IntegerField(blank=True),
        ),
    ]
