# Generated by Django 3.0.3 on 2020-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore_app', '0002_auto_20200711_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='cc',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='attack',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attack',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attack',
            name='dpt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attack',
            name='host',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attack',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attack',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attack',
            name='postalcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='attack',
            name='proto',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='attack',
            name='spt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attack',
            name='src',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attack',
            name='srcstr',
            field=models.GenericIPAddressField(),
        ),
    ]
