# Generated by Django 3.0.3 on 2020-07-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore_app', '0003_auto_20200711_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='locale',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='localeabbr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='postalcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
