# Generated by Django 3.0.3 on 2020-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore_app', '0004_auto_20200711_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='dpt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='spt',
            field=models.IntegerField(null=True),
        ),
    ]
