# Generated by Django 3.0.3 on 2020-07-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore_app', '0005_auto_20200711_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
