# Generated by Django 3.0.3 on 2020-07-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore_app', '0007_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
